### ISSUE TITLE
Deleting folder with subdirectories

### ISSUE THREAD

**Issue by marcandrews** [Equals182/eqFTP#166]
When trying to delete a folder with subdirectories, I receive the following error:

```
[node-error 7:42:23 AM] [Launcher] uncaught exception at top level, exiting. TypeError: Object #<Object> has no method 'replace'
    at Ftp.doQueue (C:\Users\Marc\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:228:70)
    at Ftp.raw (C:\Users\Marc\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:221:14)
    at Ftp.sendCommand (C:\Users\Marc\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:302:10)
    at Ftp.ls (C:\Users\Marc\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:337:10)
    at Object._commands.connection.connect.callback (C:\Users\Marc\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:1188:92)
    at Object._commands.connection.connect (C:\Users\Marc\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:415:40)
    at Object._commands.service.getPath (C:\Users\Marc\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:1160:42)
    at Object._commands.connection.connect.callback (C:\Users\Marc\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:1972:67)
    at Object._commands.service.getRemoteRoot (C:\Users\Marc\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:1079:36)
    at Object._commands.service.auth.callback (C:\Users\Marc\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:391:71)NodeDebugUtils.js:114 handleLogEvent/utils/EventDispatcher.js:222 trigger/utils/EventDispatcher.js:260 triggerWithArray/utils/NodeConnection.js:479 NodeConnection._receive
```

This causes the gear to spin endlessly, requiring a Brackets refresh or even a force-close.

v0.7.0

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
