### ISSUE TITLE
server connection keeps timing out

### ISSUE THREAD

**Issue by 517Design** [Equals182/eqFTP#213]
I really like brackets and eqFTP and want to continue using them BUT....

This is freak'n driving me nuts!!!!! Can't you fix this? I mean what the heck!! How can I use an FTP uploader that keeps timing out after a few minutes. Really the solution is to keep re-loading brackets!!! I spend more time reloading brackets then I do writing code.

Am i missing something or is this the way it is????? If so, Wow! Really...

I'm sure your busy but please answer my posts/issues. I've sent a few but none have been answered

**Comment by Equals182** [comment]
Hi

If you set keep alive (setting in [advanced tab](http://equals182.github.io/eqFTP/#advanced-tab)) to > 0, then it should send NOOP commands to your server. If your server doesn't treat them properly (resetting timeout after every noop), well..rip. To see if NOOP commands are sending check logs ([here's how, from 2 step](http://equals182.github.io/eqFTP/#creating-issue)).

You can try setting keep alive interval to 0 which should disconnect from your server after each request. You can also try disconnecting from currently connected server using switch in interface (lower panel of eqftp) and connecting to it again when connection timed out.

**Comment by 517Design** [comment]
Thanks, I'll do that and get back with you.

**Comment by 517Design** [comment]
What do I set the time offset to?

**Comment by Equals182** [comment]
time offset is just for date modified column, nothing more

**Comment by 517Design** [comment]
K

**Comment by 517Design** [comment]
Setting the keep alive to 0 worked. Awesome! Simple fix, great! I tried different settings but never thought to use 0. Now eqFTP and Brackets are perfect!

PS: Sorry about the tone of my question, was getting a little frustrated.

**Comment by 517Design** [comment]
Spoke too soon. Still having trouble. Now it connects and disconnets from the server at the same time. Here is the error in counsel:

/thirdparty/react.js:4486 Download the React DevTools for a better development experience: http://fb.me/react-devtools
/utils/DeprecationWarning.js:90 PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:325:28)
    at Object.eval (/utils/Resizer.js:560:24)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at Object.<anonymous> (file:///Users/MacPro1/Library/Application%20Support/Brackets/extensions/user/bigeyex.brackets-sftp-upload/modules/DataStorageManager.js:19:5)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at Object.eval (/./ParfaitAPI.js:126:5)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at Object.eval (/./ParfaitAPI.js:127:5)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at Object.eval (/./ParfaitAPI.js:128:5)
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at registerListeners (file:///Users/MacPro1/Library/Application%20Support/Brackets/extensions/user/bigeyex.brackets-sftp-upload/main.js:237:32)
    at file:///Users/MacPro1/Library/Application%20Support/Brackets/extensions/user/bigeyex.brackets-sftp-upload/main.js:298:9
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27220)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at registerListeners (file:///Users/MacPro1/Library/Application%20Support/Brackets/extensions/user/bigeyex.brackets-sftp-upload/main.js:238:31)
    at file:///Users/MacPro1/Library/Application%20Support/Brackets/extensions/user/bigeyex.brackets-sftp-upload/main.js:298:9
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27220)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at file:///Users/MacPro1/Library/Application%20Support/Brackets/extensions/user/bigeyex.brackets-sftp-upload/main.js:323:9
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27220)
    at Object.d.always (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:28096)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at file:///Users/MacPro1/Library/Application%20Support/Brackets/extensions/user/bigeyex.brackets-sftp-upload/main.js:326:9
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27220)
    at Object.d.always (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:28096)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at file:///Users/MacPro1/Library/Application%20Support/Brackets/extensions/user/bigeyex.brackets-sftp-upload/main.js:331:9
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27220)
    at Object.d.always (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:28096)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at file:///Users/MacPro1/Library/Application%20Support/Brackets/extensions/user/bigeyex.brackets-sftp-upload/main.js:334:9
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27220)
    at Object.d.always (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:28096)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at Object.registerMainPanel (/./MainPanel.js:293:9)
    at _appReadyHandler (/main.js:281:19)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27220)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at Object._initParfaitControlsPopup [as initParfaitControlsPopup] (/./ParfaitPopup.js:112:9)
    at _appReadyHandler (/main.js:282:22)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27220)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at _appReadyHandler (/main.js:285:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27220)
    at Object.d.always (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:28096)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at _attachExtensionManagerListener (/main.js:118:9)
    at _appReadyHandler (/main.js:289:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27220)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at _setupAbandonmentEvents (/main.js:234:9)
    at _appReadyHandler (/main.js:291:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27220)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:405)
    at _appReadyHandler (/main.js:294:9)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27220)
    at Object.d.always (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:28096)
main.js:1618 [eqFTP] Loaded (v0.7.2)
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: Adding connections.
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 0
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: "COLIN PREST INSPIRE REALITY"
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 1
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: "517 Design"
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 2
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: "Pro Services Contractors"
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 3
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: "INSPIRE DEREK SERVER"
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 4
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: "DAILY DEALS PETER FRANCO"
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 136: Checking connection ID: 5
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: "MEDICAL WORLD DIGI DONKEY"
NodeDebugUtils.js:117 [node-log 10:03:35 AM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 10:03:38 AM] [eqFTP-ftpDomain]: 1870: [q.a] Queuer is NOT ignored, continueing
NodeDebugUtils.js:117 [node-log 10:03:38 AM] [eqFTP-ftpDomain]: 1901: [q.a] Queue updated: {"a":[{"type":"folder","connectionID":5,"path":"","id":"f_1457964218558894","state":"opened","queue":"a"}],"p":[],"f":[],"s":[]}
main.js:1629 Object {event: "queue_update", connectionID: 5, element: Object}
main.js:1629 Object {event: "working", work: true}
main.js:1629 Object {event: "queue_update", connectionID: 5, element: Object}
NodeDebugUtils.js:117 [node-log 10:03:38 AM] [eqFTP-ftpDomain]: Connecting to this ID: 5
main.js:1629 Object {event: "server_connecting", connectionID: 5}
NodeDebugUtils.js:117 [node-log 10:03:38 AM] [eqFTP-ftpDomain]: Connecting...
main.js:1629 Object {event: "server_connect", connectionID: 5}
NodeDebugUtils.js:117 [node-log 10:03:38 AM] [eqFTP-ftpDomain]: Connected...
NodeDebugUtils.js:117 [node-log 10:03:38 AM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:38 AM] {
  "code": 220,
  "text": "220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------\n220-You are user number 6 of 500 allowed.\n220-Local time is now 07:03. Server port: 21.\n220-This is a private system - No anonymous login\n220 You will be disconnected after 3 minutes of inactivity.",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:38 AM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 10:03:38 AM] "user ddproduction"
NodeDebugUtils.js:117 [node-log 10:03:38 AM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:38 AM] {
  "code": 331,
  "text": "331 User ddproduction OK. Password required",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:38 AM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 10:03:38 AM] "pass D!g!D0nk3y"
NodeDebugUtils.js:117 [node-log 10:03:38 AM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:38 AM] {
  "code": 230,
  "text": "230 OK. Current directory is /",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:38 AM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 10:03:38 AM] "feat"
NodeDebugUtils.js:117 [node-log 10:03:38 AM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:38 AM] {
  "code": 211,
  "text": "211-Extensions supported:\n EPRT\n IDLE\n MDTM\n SIZE\n MFMT\n REST STREAM\n MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;\n MLSD\n AUTH TLS\n PBSZ\n PROT\n UTF8\n TVFS\n ESTA\n PASV\n EPSV\n SPSV\n ESTP\n211 End.",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:38 AM] [eqFTP-ftpDomain]: [s.gRR] Getting remote root for this ID: 5
NodeDebugUtils.js:117 [node-log 10:03:38 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 5
NodeDebugUtils.js:117 [node-log 10:03:38 AM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 10:03:38 AM] "pwd"
NodeDebugUtils.js:117 [node-log 10:03:39 AM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:39 AM] {
  "code": 257,
  "text": "257 \"/\" is your current location",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:39 AM] [eqFTP-ftpDomain]: [s.gRR] Remote root for this ID: 5 is /
NodeDebugUtils.js:117 [node-log 10:03:39 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 5
NodeDebugUtils.js:117 [node-log 10:03:39 AM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 10:03:39 AM] "TYPE I"
NodeDebugUtils.js:117 [node-log 10:03:39 AM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:39 AM] {
  "code": 200,
  "text": "200 TYPE is now 8-bit binary",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:39 AM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 10:03:39 AM] "PASV"
NodeDebugUtils.js:117 [node-log 10:03:39 AM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:39 AM] {
  "code": 227,
  "text": "227 Entering Passive Mode (97,74,188,75,198,207)",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:39 AM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 10:03:39 AM] "LIST /"
NodeDebugUtils.js:117 [node-log 10:03:39 AM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:39 AM] {
  "code": 150,
  "text": "150 Accepted data connection",
  "isMark": true,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:39 AM] DEBUG:  server_response
NodeDebugUtils.js:117 [node-log 10:03:39 AM] {
  "code": 226,
  "text": "226-Options: -a -l \n226 39 matches total",
  "isMark": false,
  "isError": false
}
NodeDebugUtils.js:117 [node-log 10:03:39 AM] DEBUG:  eqFTP-LISTING
NodeDebugUtils.js:117 [node-log 10:03:39 AM] "drwx---r-x   14 4952635    inetuser         4096 Mar 14 06:37 .\r\ndrwx---r-x   14 4952635    inetuser         4096 Mar 14 06:37 ..\r\ndrwx---r-x    3 4952635    inetuser         4096 Mar 12 11:15 .sass-cache\r\n-rw----r--    1 4952635    inetuser         8219 Mar 13 07:30 Untitled-1.html\r\n-rw----r--    1 4952635    inetuser        23243 Mar 12 11:15 about.html\r\n-rw----r--    1 4952635    inetuser        17538 Mar 12 11:15 blank-page.html\r\n-rw----r--    1 4952635    inetuser        25460 Mar 12 11:15 blog-post.html\r\n-rw----r--    1 4952635    inetuser        24394 Mar 12 11:15 blog.html\r\ndrwx---r-x    5 4952635    inetuser         4096 Mar 12 11:15 bootstrap\r\ndrwx---r-x    5 4952635    inetuser         4096 Mar 12 11:14 bootstrapORIGINAL\r\n-rw----r--    1 4952635    inetuser          200 Mar 12 11:15 config.rb\r\n-rw----r--    1 4952635    inetuser        21025 Mar 12 11:15 contact.html\r\ndrwx---r-x    3 4952635    inetuser         4096 Mar 13 08:07 css\r\n-rw----r--    1 4952635    inetuser        32633 Mar 12 11:15 element.html\r\n-rw----r--    1 4952635    inetuser        17648 Mar 12 11:15 error.html\r\n-rw----r--    1 4952635    inetuser        25964 Mar 12 11:15 faq.html\r\ndrwx---r-x    6 4952635    inetuser         4096 Mar 12 11:16 font-awesome-4.4.0\r\ndrwx---r-x    2 4952635    inetuser         4096 Mar 12 11:16 fonts\r\n-rw----r--    1 4952635    inetuser        18252 Mar 12 11:15 home-soon.html\r\ndrwx---r-x    4 4952635    inetuser         4096 Mar 14 06:41 img\r\n-rw----r--    1 4952635    inetuser        50381 Mar 14 06:50 index.html\r\n-rw----r--    1 4952635    inetuser        41274 Mar 12 12:18 indexORIGINAL.html\r\n-rw----r--    1 4952635    inetuser        41291 Mar 12 16:18 indexTest.html\r\ndrwx---r-x    2 4952635    inetuser         4096 Mar 12 15:51 js\r\n-rw----r--    1 4952635    inetuser        18708 Mar 12 11:15 login-register.html\r\n-rw----r--    1 4952635    inetuser           43 Mar 13 09:32 medicaid-world-jpg.html\r\ndrwx---r-x    3 4952635    inetuser         4096 Mar 12 11:16 nbproject\r\ndrwx---r-x    6 4952635    inetuser         4096 Mar 12 05:03 original-files-3-12-16\r\ndrwx---r-x    2 4952635    inetuser         4096 Mar 12 15:51 portfilter-master\r\n-rw-r--r--    1 4952635    inetuser        26126 Mar 12 15:07 portfolio-filter.html\r\n-rw----r--    1 4952635    inetuser        20479 Mar 12 11:15 portfolio-single.html\r\n-rw----r--    1 4952635    inetuser        24287 Mar 12 11:15 pricing.html\r\n-rw----r--    1 4952635    inetuser        18081 Mar 12 11:15 psw-recover.html\r\ndrwx---r-x    2 4952635    inetuser         4096 Mar 12 11:16 scss\r\n-rw----r--    1 4952635    inetuser        23020 Mar 12 11:15 services.html\r\n-rw----r--    1 4952635    inetuser        20139 Mar 12 11:15 side-nav.html\r\n-rw----r--    1 4952635    inetuser         5113 Mar 13 08:18 tabs.html\r\n-rw----r--    1 4952635    inetuser       127171 Mar 13 08:21 tabs2.html\r\n-rw----r--    1 4952635    inetuser        29065 Mar 12 11:15 team.html\r\n"
NodeDebugUtils.js:117 [node-log 10:03:39 AM] [eqFTP-ftpDomain]: 1180: [s.gP] Got Directory: /
NodeDebugUtils.js:117 [node-log 10:03:39 AM] [eqFTP-ftpDomain]: [q.p] Got folder: /
main.js:1629 Object {event: "directory_got", err: null, files: Array[37], path: "", connectionID: 5…}
NodeDebugUtils.js:117 [node-log 10:03:39 AM] [eqFTP-ftpDomain]: Disconnecting...
main.js:1629 Object {event: "server_disconnecting", connectionID: 5}
2NodeDebugUtils.js:117 [node-log 10:03:39 AM] [eqFTP-ftpDomain]: [c.c] ftpDomain currently disconnecting from: 5
NodeDebugUtils.js:117 [node-log 10:03:39 AM] [eqFTP-ftpDomain]: Disonnected.
main.js:1629 Object {event: "server_disconnect", connectionID: 5}
main.js:1629 Object {event: "working", work: false}
NodeDebugUtils.js:117 [node-log 10:03:39 AM] [eqFTP-ftpDomain]: [q.p] Queue is empty

**Comment by Equals182** [comment]
But that's the point. It should disconnect right after request. Do you see folders, can download/upload files?

**Comment by 517Design** [comment]
OK lol. If it disconnects right after request, how can I continue to upload files. Maybe that's a dumb question.

I see folders/files but I can't upload anything. Have to shut and reopen brackets. Then click the X on the file I want to update on the working files section. Then connect to server and reopen the file again. Now I can edit it and upload by command + s

**Comment by Equals182** [comment]
you should be able to upload them just by ctrl+s or right click on local files. It should connect, upload and then disconnect automatically. If it's not - check automatization tab: if your automatization is Classic - check Even If Disconnected. If it's Sync - check File update option.
I just tried ctrl+s without connecting to server and it worked fine (I'm using Sync)

**Comment by 517Design** [comment]
Thanks

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
