### ISSUE TITLE
Latest v1.7 breaks eqFTP

### ISSUE THREAD

**Issue by nikolafilipovic** [Equals182/eqFTP#224]
Posting the console dump, I hope it helps. I will be downgrading back to 1.6 and I suggest everyone who uses eqFTP do the same.

`WebSocket connection to 'ws://localhost:47386/' failed: Unexpected response code: 401 /utils/NodeConnection.js:89
Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at Object.<anonymous> (Brackets/extensions/user/equals182.eqftp/main.js:384:29) /utils/DeprecationWarning.js:90
Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at Object.<anonymous> (Brackets/extensions/user/equals182.eqftp/main.js:385:29) /utils/DeprecationWarning.js:90
Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at Object.<anonymous> (Brackets/extensions/user/equals182.eqftp/main.js:386:26) /utils/DeprecationWarning.js:90
Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at Object.<anonymous> (Brackets/extensions/user/equals182.eqftp/main.js:387:28) /utils/DeprecationWarning.js:90
Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at Object.<anonymous> (Brackets/extensions/user/equals182.eqftp/main.js:388:26) /utils/DeprecationWarning.js:90
Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at Object.<anonymous> (Brackets/extensions/user/equals182.eqftp/main.js:389:29) /utils/DeprecationWarning.js:90
Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at Object.<anonymous> (Brackets/extensions/user/equals182.eqftp/main.js:390:28) /utils/DeprecationWarning.js:90
Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:125:32)
    at Object.<anonymous> (Brackets/extensions/user/equals182.eqftp/main.js:391:26) /utils/DeprecationWarning.js:90`

P.S.

Awesome plugin!

**Comment by FurmanSK** [comment]
Yep. It was working for a few then just started getting this same problem. Won't upload now.

WebSocket connection to 'ws://localhost:58262/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
NodeDebugUtils.js:56 [NodeDebugUtils] Node is listening on port 58348

How can we downgrade to 1.6 again?

**Comment by FurmanSK** [comment]
Ah, ok so mine seemed to be a permissions issue. Some how my web server had files change from me owning them to root owning them. Once I changed permissions of all files in my web directory to me owning them, all is good.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
