### ISSUE TITLE
SFTP Can't connect using key generated with PuttyGen

### ISSUE THREAD

**Issue by onjaG** [Equals182/eqFTP#254]
i have the error bellow using the key:

> ErrorNotification.js:122 [node-error 4:15:42 PM] Error: Cannot parse privateKey: Unsupported key format
    at Connection.connect (D:\Utilisateurs\onja\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\scp2\node_modules\ssh2\lib\Connection.js:287:13)
    at Client.sftp (D:\Utilisateurs\onja\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\scp2\lib\client.js:94:7)
    at Object._commands.connection.createClient (D:\Utilisateurs\onja\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:312:88)
    at Object._commands.connection.connect [as connect] (D:\Utilisateurs\onja\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:382:50)
    at Object._commands.queue.process (D:\Utilisateurs\onja\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:1946:54)
    at D:\Utilisateurs\onja\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:1909:45
    at Object._commands.service.diff.ignore.checkSingle (D:\Utilisateurs\onja\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:1317:37)
    at Connection._commands.queue.add (D:\Utilisateurs\onja\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:1867:51)
    at Object.executeCommand (C:\Program Files (x86)\Brackets\node-core\DomainManager.js:174:45)
    at Connection._receive (C:\Program Files (x86)\Brackets\node-core\ConnectionManager.js:112:27)

>

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
