### ISSUE TITLE
epFTP v1.0 not uploading on save

### ISSUE THREAD

**Issue by scottkoons** [Equals182/eqFTP#274]
My files do not save on upload nor do files sync when I create a new file in the local folder.  I am using Brackets 1.8 epFTP v1.0 on a Mac osSierra.

Even when I right click on the file and hit upload nothing happens.  Any ideas?
<img width="359" alt="screen shot 2017-02-09 at 3 56 10 pm" src="https://cloud.githubusercontent.com/assets/16785252/22806633/53519680-eee0-11e6-8eb3-f528893fb63c.png">

**Comment by Equals182** [comment]
Can you please attach console output?

0. Turn on Debug in eqFTP settings
1. Press F12 in Brackets' main window
2. Open console tab
3. Reproduce the bug
4. Copy and edit log, remove connections' credentials
5. Paste here using ``` to format logs

**Comment by scottkoons** [comment]
Here are the logs for trying to upload a new file:

> Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at renderContent (file:///Users/scottkoons/Library/Application%20Support/Brackets/extensions/user/brackets-minimap/MiniMapViewManager.js:574:22)
    at Object.<anonymous> (file:///Users/scottkoons/Library/Application%20Support/Brackets/extensions/user/brackets-minimap/MiniMapViewManager.js:728:42)
    at Function.n.extend.each (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:19:2882)
    at n.fn.n.each (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:19:847)
    at Object.change (file:///Users/scottkoons/Library/Application%20Support/Brackets/extensions/user/brackets-minimap/MiniMapViewManager.js:678:23)
    at onDocumentChange (file:///Users/scottkoons/Library/Application%20Support/Brackets/extensions/user/brackets-minimap/Minimap.js:43:21)
    at Document.trigger (/utils/EventDispatcher.js:229:40)
    at Document._notifyDocumentChange (/document/Document.js:341:14)
NodeDebugUtils.js:114 [node-log 11:07:57 AM] [eqFTP node] [watcher] RAW change /Applications/MAMP/htdocs/CMB-jun16/eq.html { curr: 
   { dev: 16777220,
     mode: 33188,
     nlink: 1,
     uid: 501,
     gid: 20,
     rdev: 0,
     blksize: 4096,
     ino: 25942159,
     size: 17,
     blocks: 8,
     atime: 2017-02-10T18:06:48.000Z,
     mtime: 2017-02-10T18:07:57.000Z,
     ctime: 2017-02-10T18:07:57.000Z,
     birthtime: 2017-02-09T18:53:42.000Z },
  prev: 
   { dev: 16777220,
     mode: 33188,
     nlink: 1,
     uid: 501,
     gid: 20,
     rdev: 0,
     blksize: 4096,
     ino: 25942159,
     size: 13,
     blocks: 8,
     atime: 2017-02-10T18:06:48.000Z,
     mtime: 2017-02-09T21:14:21.000Z,
     ctime: 2017-02-09T21:14:21.000Z,
     birthtime: 2017-02-09T18:53:42.000Z } }
NodeDebugUtils.js:114 [node-log 11:07:58 AM] [eqFTP node] [watcher] change eq.html { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 25942159,
  size: 17,
  blocks: 8,
  atime: 2017-02-10T18:06:48.000Z,
  mtime: 2017-02-10T18:07:57.000Z,
  ctime: 2017-02-10T18:07:57.000Z,
  birthtime: 2017-02-09T18:53:42.000Z }
NodeDebugUtils.js:114 [node-log 11:07:58 AM] [eqFTP node] eqftp.cache._recently_downloaded undefined
/filesystem/impls/appshell/AppshellFileSystem.js:119 FileWatcherDomain was expected to deliver stats for changed event!

Here is the log for trying to upload an already existing file:

> FileWatcherDomain was expected to deliver stats for changed event!
NodeDebugUtils.js:114 [node-log 11:10:08 AM] [eqFTP node] [watcher] RAW change /Applications/MAMP/htdocs/CMB-jun16/Layouts/OnlineShop/shopping_cart-US.html { curr: 
   { dev: 16777220,
     mode: 33188,
     nlink: 1,
     uid: 501,
     gid: 20,
     rdev: 0,
     blksize: 4096,
     ino: 13238775,
     size: 4024,
     blocks: 8,
     atime: 2017-02-10T18:09:52.000Z,
     mtime: 2017-02-10T18:10:08.000Z,
     ctime: 2017-02-10T18:10:08.000Z,
     birthtime: 2016-08-25T21:45:21.000Z },
  prev: 
   { dev: 16777220,
     mode: 33188,
     nlink: 1,
     uid: 501,
     gid: 20,
     rdev: 0,
     blksize: 4096,
     ino: 13238775,
     size: 4021,
     blocks: 8,
     atime: 2017-02-10T18:09:52.000Z,
     mtime: 2017-02-09T22:59:39.000Z,
     ctime: 2017-02-09T22:59:39.000Z,
     birthtime: 2016-08-25T21:45:21.000Z } }
/filesystem/impls/appshell/AppshellFileSystem.js:119 FileWatcherDomain was expected to deliver stats for changed event!
NodeDebugUtils.js:114 [node-log 11:10:09 AM] [eqFTP node] [watcher] change Layouts/OnlineShop/shopping_cart-US.html { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 13238775,
  size: 4024,
  blocks: 8,
  atime: 2017-02-10T18:09:52.000Z,
  mtime: 2017-02-10T18:10:08.000Z,
  ctime: 2017-02-10T18:10:08.000Z,
  birthtime: 2016-08-25T21:45:21.000Z }
NodeDebugUtils.js:114 [node-log 11:10:09 AM] [eqFTP node] eqftp.cache._recently_downloaded []

**Comment by scottkoons** [comment]
Here is an error when I have auto upload and check for differenced checked:

> [eqFTP main] eqFTP:event Object {action: "connection:ready", data: Object}
NodeDebugUtils.js:114 [node-log 11:11:46 AM] [eqFTP node] connected to server, firing callback function () {
        if (--n > 0) {
          result = func.apply(this, arguments);
        }
        if (n <= 1) {
          func = undefined;
        }
        return result;
      }
NodeDebugUtils.js:114 [node-log 11:11:46 AM] [eqFTP node] opening connection result null
NodeDebugUtils.js:111 [node-error 11:11:47 AM] [Launcher] uncaught exception at top level, exiting. TypeError: Cannot read property 'indexOf' of undefined
    at EFTP.getRealRemotePath (/Users/scottkoons/Library/Application Support/Brackets/extensions/user/equals182.eqftp/node/libs/eftp/index.js:346:11)
    at EFTP.cd (/Users/scottkoons/Library/Application Support/Brackets/extensions/user/equals182.eqftp/node/libs/eftp/index.js:442:17)
    at /Users/scottkoons/Library/Application Support/Brackets/extensions/user/equals182.eqftp/node/libs/eftp/index.js:553:16
    at /Users/scottkoons/Library/Application Support/Brackets/extensions/user/equals182.eqftp/node/libs/eftp/index.js:502:23
    at /Users/scottkoons/Library/Application Support/Brackets/extensions/user/equals182.eqftp/node/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:1526:13
    at SFTPStream._transform (/Users/scottkoons/Library/Application Support/Brackets/extensions/user/equals182.eqftp/node/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/scottkoons/Library/Application Support/Brackets/extensions/user/equals182.eqftp/node/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)handleLogEvent @ NodeDebugUtils.js:111trigger @ /utils/EventDispatcher.js:229triggerWithArray @ /utils/EventDispatcher.js:267NodeConnection._receive @ /utils/NodeConnection.js:474
NodeDebugUtils.js:111 [node-info 11:11:47 AM] [Server] stopping
/filesystem/FileSystem.js:965 File watchers went offline!
10/utils/NodeConnection.js:84 WebSocket connection to 'ws://localhost:62900/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
/filesystem/FileSystem.js:973 Watching disabled for /Applications/MAMP/htdocs/CMB-jun16/
NodeDebugUtils.js:114 [node-log 11:11:49 AM] Node:  v6.3.1
