### ISSUE TITLE
Unable to upload any folders on FTP connection

### ISSUE THREAD

**Issue by blairdow** [Equals182/eqFTP#283]
## Expected vs Current Behavior
When I right click on a folder in Brackets left side menu and select Upload, I get an error in EQFTP that says "There was an error uploading: ". Single file upload is fine, the issue is with folders/directories.

## Steps to Reproduce (for bugs)
1. Create new folder or edit files in folder in local project file.
2. Select 'upload'

## Debug Information
The error in debug mode is ```[node-log 12:21:31 PM] [eqFTP node] cached queue true [ { qid: '1bb749aqb-293',
    id: '1babgor70',
    act: 'upload',
    args: [ [Object], [Function], [Function] ],
    queue: 'f',
    err: 
     Error: Local path cannot be a directory
         at /Users/blairdowis/Library/Application Support/Brackets/extensions/user/equals182.eqftp/node/libs/eftp/index.js:155:25
         at FSReqWrap.oncomplete (fs.js:123:15) } ]```

I can send full log if necessary...

* eqFTP version: beta 1.0
* Brackets version: 1.8
* Operating System and version: mac os Sierra 10.12.3

**Comment by Equals182** [comment]
thank you for reporting this bug. unfortunately there's no folder uploading in current version at all. It has an option to do so, but nah, there's no way to upload folders as for now.
I thought about adding this thing, of course. No ETA, though. It's that time again when I don't have time and passion to work on eqftp, sorry.

**Comment by blairdow** [comment]
Ahh sad face :( Thanks for getting back to me. EQFTP is great aside from that!
