### ISSUE TITLE
Request to http://185.146.171.46/eqFTP failed

### ISSUE THREAD

**Issue by anephew** [Equals182/eqFTP#284]
Hello!

I see some log in the console. Where the extension tries to connect? http://185.146.171.46/eqFTP ?

```
[node-log 2:55:10 PM] { FetchError: request to http://185.146.171.46/eqFTP failed, reason: connect ETIMEDOUT 185.146.171.46:80
    at ClientRequest.<anonymous> (C:\Users\anephew\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'FetchError',
  message: 'request to **http://185.146.171.46/eqFTP** failed, reason: connect ETIMEDOUT 185.146.171.46:80',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }
```

* eqFTP version: v1.0.0-beta.1
* Brackets version: 1.8
* Operating System and version: Windows 10 x64 (14393.693)

**Comment by Equals182** [comment]
Yeah, it was kind of "tracker" that sent once-randomly-generated-id to my server so I could see some stats, like, how many people are using eqftp at moment. My server's IP changed so I commented out this [part of code](https://github.com/Equals182/eqFTP/blob/master/node/libs/tracker.js#L34)
You can check source code to see that no personal data of any kind is sent there.
So yeah, you can just update from repo and it will be gone and no stats will be ever sent again.

**Comment by Equals182** [comment]
Here's how db looks inside, in case you're interested
![image](https://cloud.githubusercontent.com/assets/4254803/23948095/8f0ed760-0992-11e7-8f6b-1acc073d858e.png)

**Comment by anephew** [comment]
@Equals182 Пытаюсь разобраться с ошибками в консоли у установленных расширений, поэтому и написал. Спасибо за ответ!
