### ISSUE TITLE
ECONNRESET и другие ошибки в соединении

### ISSUE THREAD

**Issue by anephew** [Equals182/eqFTP#289]
Приветствую!

Есть такая проблема, и довольна частая. Во-первых ошибка ECONNRESET, я так понимаю это на стороне ftp сервера, когда соединение разъединяется, и еще какая-то бывает ошибка. Дело в том что после этого перезагрузить соединение (например нажать на connect в списке соединений или через лупу в шапке) не получается (ничего не происходит, ни в углу никаких новых оповещений на текущее время, ни в консоли новых ошибок), приходится перезагружать весь Brackets, что уже прилично надоело (  В любом другом ftp клиенте как минимум можно разорвать соединение и снова подключиться, но явно не перезагружать программу... 

![image](https://cloud.githubusercontent.com/assets/551514/24325790/ab2e9ecc-11b1-11e7-98bf-59166553ff60.png)

Вот кусок лога, там например есть упоминание main.js:130 (/Brackets/extensions/user/equals182.eqftp/main.js)

Как-то так.

```
/utils/EventDispatcher.js:231 Exception in 'keyup' listener on Editor$el: (...)get $el: ()_$messagePopover: null_codeMirror: CodeMirror_currentOptions: Object_doWorkingSetSync: ()_duringSync: false_eventHandlers: Object_focused: false_handleDocumentChange: ()_handleDocumentDeleted: ()_handleDocumentLanguageChanged: ()_hideMarks: Array[0]_hostEditor: null_inlineWidgetQueues: Object_inlineWidgets: Array[0]_lastEditorWidth: 1024_paneId: "first-pane"document: Documentoff: (events, fn)on: (events, fn)scrollTop: (...)get scrollTop: ()__proto__: Object TypeError: Cannot set property type of #<Event> which has only a getter TypeError: Cannot set property type of #<Event> which has only a getter
    at CodeHintList.callMoveUp (/editor/CodeHintList.js:521:20)
    at _updateHintList (/editor/CodeHintManager.js:428:29)
    at _handleKeyupEvent (/editor/CodeHintManager.js:574:17)
    at Editor.trigger (/utils/EventDispatcher.js:229:40)
    at _onKeyEvent (/editor/Editor.js:989:18)
    at signal (/thirdparty/CodeMirror/lib/codemirror.js:1246:59)
    at signalDOMEvent (/thirdparty/CodeMirror/lib/codemirror.js:1255:3)
    at CodeMirror.onKeyUp [as triggerOnKeyUp] (/thirdparty/CodeMirror/lib/codemirror.js:6859:3)
    at HTMLTextAreaElement.eval (/thirdparty/CodeMirror/lib/codemirror.js:7529:50)trigger @ /utils/EventDispatcher.js:231
/utils/EventDispatcher.js:232 Assertion failed:trigger @ /utils/EventDispatcher.js:232
/utils/EventDispatcher.js:231 Exception in 'keyup' listener on Editor TypeError: Cannot set property type of #<Event> which has only a getter TypeError: Cannot set property type of #<Event> which has only a getter
    at CodeHintList.callMoveUp (/editor/CodeHintList.js:521:20)
    at _updateHintList (/editor/CodeHintManager.js:428:29)
    at _handleKeyupEvent (/editor/CodeHintManager.js:574:17)
    at Editor.trigger (/utils/EventDispatcher.js:229:40)
    at _onKeyEvent (/editor/Editor.js:989:18)
    at signal (/thirdparty/CodeMirror/lib/codemirror.js:1246:59)
    at signalDOMEvent (/thirdparty/CodeMirror/lib/codemirror.js:1255:3)
    at CodeMirror.onKeyUp [as triggerOnKeyUp] (/thirdparty/CodeMirror/lib/codemirror.js:6859:3)
    at HTMLTextAreaElement.eval (/thirdparty/CodeMirror/lib/codemirror.js:7529:50)trigger @ /utils/EventDispatcher.js:231
/utils/EventDispatcher.js:232 Assertion failed:trigger @ /utils/EventDispatcher.js:232
main.js:130 There was an error on domain.ru connection: ECONNRESETeqftp.log @ main.js:130
ui.js:1412 98 80
ui.js:1412 640 300
ui.js:1412 98 80
main.js:823 Uncaught TypeError: Cannot read property 'getLanguageForSelection' of null
```

* eqFTP version: из репозитория (взято вчера). eqFTP v1.0.0-beta.1 из ветки releases так же имеет эту проблему.
* Brackets 1.9
* Windows 10 x64 1607 (14393.953)

**Comment by anephew** [comment]
Перезагружал час назад Brackets из-за проблемы выше. Все было ок, открывал файлы с ftp сервера (хостинг agava), делал правки, сохранял. И вот опять: только что сохранил файл, потом стал открывать другой с сервера и снова ошибка справа снизу - There was an error on domain.ru connection: ECONNRESET, в консоли:

```
There was an error on domain.ru connection: ECONNRESETeqftp.log @ main.js:130
```
И ничего не сделать, открыто более 15 файлов, которые в работе и теперь придется перезагружать Brackets и снова искать-загружать файлы из папок на сервере. Работать невозможно (

**Comment by anephew** [comment]
https://github.com/sitegui/nodejs-websocket/issues/26

> ECONNRESET (Connection reset by peer): A connection was forcibly closed by a peer. This normally results from a loss of the connection on the remote socket due to a timeout or reboot. Commonly encountered via the http and net modules.

Полагаю нужно сделать так, чтобы поддерживалось соединение, по-моему это есть в ftp клиентах. В Total Commander например у меня тоже отсоединяется от сервера, но мне достаточно сделать refresh (ctrl+r) и файлы из Brackets снова сохраняются на сервер. В случае с eqFTP получается что и refresh текущего соединения не сделать, а значит проблема будет всегда.
