### ISSUE TITLE
Auto uploading error in Windows 8.1

### ISSUE THREAD

**Issue by randallflagg34** [Equals182/eqFTP#89]
Every sometime I got an error in the plugin.

`node-error 11:18:30 AM] [Launcher] uncaught exception at top level, exiting. TypeError: Cannot call method 'on' of undefined
    at Object.self.openPassive.callback (C:\Users\Adrian\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:262:24)
    at Object.self.raw.callback (C:\Users\Adrian\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:495:31)
    at Ftp.parseResponse (C:\Users\Adrian\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:241:38)
    at Stream.<anonymous> (C:\Users\Adrian\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:101:14)
    at Stream.EventEmitter.emit (events.js:95:17)
    at ResponseParser.reemit (C:\Users\Adrian\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\node_modules\event-stream\node_modules\duplexer\index.js:70:25)
    at ResponseParser.EventEmitter.emit (events.js:95:17)
    at ResponseParser.<anonymous> (_stream_readable.js:746:14)
    at ResponseParser.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)extensions/default/DebugCommands/ErrorNotification.js:125 window.console.error`
and then this: 
`WebSocket connection to 'ws://localhost:51058/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

This are the errors I get.
Do you think is the Windows or a problem un my machine?

**Comment by Equals182** [comment]
Hmm.. I'm working on Win8.1 and didn't saw this error before. 
So it's not a perennial issue, is it? I mean, is it working fine most of times and then randomly gives you error or you getting error every time you trying to use eqFTP?

**Comment by randallflagg34** [comment]
Me too, Win 8.1.
No, it happends randomly. When I'm working, like it happend just now, boom, it won't upload and I have to refresh Brackets.
Maybe is crashing with another plugin? BTW, just to be sure, I turn off the Firewall.
This happend after my lunch brake of leaving my Brackets open (not letting me upload):

`Exception in 'editorChange' listener on Editor$el: (...)get $el: function () {_$messagePopover: null_codeMirror: CodeMirror_currentOptions: Object_duringSync: false_eventHandlers: Object_focused: false_handleDocumentChange: function () { [native code] }_handleDocumentDeleted: function () { [native code] }_handleDocumentLanguageChanged: function () { [native code] }_hideMarks: Array[0]_inlineWidgetQueues: Object_inlineWidgets: Array[0]_lastEditorWidth: 747document: DocumentscrollTop: (...)get scrollTop: function () {__proto__: Editor TypeError: Cannot read property '0' of null TypeError: Cannot read property '0' of null
    at WPhints.getHints (file:///C:/Users/Adrian/AppData/Roaming/Brackets/extensions/user/brackets-wp-functions-hint/main.js:114:116)
    at _updateHintList (/editor/CodeHintManager.js:420:40)
    at _handleChange (/editor/CodeHintManager.js:612:17)
    at Editor.trigger (/utils/EventDispatcher.js:222:40)
    at Editor._handleEditorChange (/editor/Editor.js:804:14)
    at eval (/editor/Editor.js:341:18)
    at Editor.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/editor/Editor.js:875:18)
    at CodeMirror.signal (/thirdparty/CodeMirror2/lib/codemirror.js:7213:49)
    at endOperation_finish (/thirdparty/CodeMirror2/lib/codemirror.js:2133:7)
/utils/EventDispatcher.js:225 Assertion failed:/utils/EventDispatcher.js:225 trigger`

**Comment by Equals182** [comment]
If it happens after a long pause for like 10+ minutes it may be a bug in eqFTP 'cause in some cases when your server disconnecting you after some time, eqFTP can't handle it right way and then everything stops working. I'm working on this bug in new version but still, I'm not sure that it's your case.

Can you turn on Debug, connect to server and post here a bunch of logs right when it happens again? Don't forget to hide personal data before publishing.

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
